---
ansible_ssh_user: root
ansible_ssh_pass: MotDePasse

pve_cluster_name: TCLOCLUSTER

master_machine: "{{groups.all[0]}}"

gluster_cmd: /sbin/gluster
gluster_mount_dir: /mnt/isofiles
gluster_brick_dir: /mnt/isofiles/briks
gluster_brick_name: iso-replica
gluster_storage_name: iso-replica-files

gluster_brick_config: "replica {{groups.all|length}} transport tcp"
