- name: install ftp mounting
  apt: 
    name: curlftpfs
    state: present

- name: add space ftp dir storage
  lineinfile:
    path: /etc/pve/storage.cfg
    line: "\n"
    state: present
  when: "inventory_hostname == master_machine"

- name: ftp dir storage
  lineinfile:
    path: /etc/pve/storage.cfg
    regex: "^.*{{item}}"
    line: "{{item}}"
    state: present
  with_items:
    - "dir: ftp-backups"
    - "  path {{backup_directory}}"
    - "  content backup"
    - "  prune-backups keep-last=7"
    - "  shared 0"
  when: inventory_hostname == master_machine


- name: create ftp mount dir systemd service file
  template:
    src: ftp.service.j2
    dest: /etc/systemd/system/mnt-backups-dump.mount
  register: ftp_mount_file

- name: create ftp mount dir systemd service file
  template:
    src: ftp.automount.j2
    dest: /etc/systemd/system/mnt-backups-dump.automount
  register: ftp_automount_file

- name: systemctl daemon-reload (redhat)
  shell: systemctl daemon-reload
  when: ftp_automount_file.changed or ftp_mount_file.changed


- name: enable ftp mount
  service:
    name: mnt-backups-dump.mount
    enabled: yes

- name: start ftp automount 
  service:
    name: mnt-backups-dump.automount
    enabled: yes
    state: started
