---
- name: copy file from template
  template: >
    src="{{item.src}}"
    dest="{{item.dest}}"
  with_items:
    - {src: nets.boot.j2, dest: /etc/tinc/nets.boot}
    - {src: tinc-up.j2, dest: "/etc/tinc/{{ netname }}/tinc-up"}
    - {src: tinc-down.j2, dest: "/etc/tinc/{{ netname }}/tinc-down"}

- name: copy new interfaces network
  template:
    src: interfaces.j2
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: '0644'

- name: ensure tinc is started
  service: >
    name=tinc
    enabled=yes
    state=restarted
    pattern=tincd -n {{ netname }}

