---
- name: install tinc vpn daemon
  apt:
    name: tinc
    state: present

- name: create tinc systemd service file (redhat)
  template: >
    src=tinc.service.j2
    dest=/etc/systemd/system/tinc.service
  register: tinc_service_file

- name: systemctl daemon-reload (redhat)
  shell: systemctl daemon-reload
  when: tinc_service_file.changed

