wget -o /mnt/isofiles/briks/centos-cloudinit.img.xz https://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud.qcow2.xz

unxz /mnt/isofiles/briks/centos-cloudinit.img.xz

qm create 9000 --memory 2048 --net0 virtio,bridge=vmbr4

qm importdisk 9000 /mnt/isofiles/briks/centos-cloudinit.img iso-replica-files

qm set 9000 --scsihw virtio-scsi-pci --scsi0 iso-replica-files:9000/vm-9000-disk-0

qm set 9000 --ide2 iso-replica-files:cloudinit

qm set 9000 --boot c --bootdisk scsi0

qm set 9000 --serial0 socket --vga serial0

qm template 9000
