---

- name: install gluster daemon
  apt:
    name: ["glusterfs-server", "glusterfs-client"]
    state: present

- name: Start glusterd
  service:
    name: glusterd
    state: started

- name: Enable glusterd
  service:
    name: glusterd
    enabled: yes

- name: Ensure Gluster brick and mount directories exist.
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: www-data
    mode: 0775
  with_items:
    - "{{ gluster_brick_dir }}"
    - "{{ gluster_mount_dir }}"

- name: Check if Gluster volumes already exist.
  shell: "{{ gluster_cmd }} volume info"
  changed_when: false
  register: gluster_volume_info

- name: Connect to Gluster peers.
  shell: "{{ gluster_cmd }} peer probe {{item}}"
  register: gluster_peer_probe
  changed_when: "'already in peer list' not in gluster_peer_probe.stdout and 'Probe on localhost not needed' not in gluster_peer_probe.stdout"
  failed_when: false
  with_items: 
    - "{{groups.all}}"
  when: "'Volume Name: gluster' not in gluster_volume_info.stdout and inventory_hostname == master_machine"

- name: Create all volume list variable 
  set_fact:
    gluster_brick_config: "{{ gluster_brick_config + ' ' + item + ':' + gluster_brick_dir }}"
  with_items: 
    - "{{groups.all}}"
  when: "inventory_hostname == master_machine"

- name: Create Gluster volume.
  shell: "{{ gluster_cmd }} volume create {{ gluster_brick_name }} {{ gluster_brick_config }} force"
  register: gluster_volume_create
  changed_when: "'successful' in gluster_volume_create.stdout"
  failed_when: "'already exists' in gluster_volume_create.stdout or 'successful' in gluster_volume_create.stdout"
  when: "inventory_hostname == master_machine and 'Volume Name: gluster' not in gluster_volume_info.stdout"

- name: Ensure Gluster volume is started.
  shell: "{{ gluster_cmd }} volume start {{ gluster_brick_name }}"
  register: gluster_volume_start
  failed_when: "'started' in gluster_volume_start.stdout"
  changed_when: "'successful' in gluster_volume_start.stdout"
  when: "inventory_hostname == master_machine and 'Volume Name: gluster' not in gluster_volume_info.stdout"

- name: Ensure Gluster storage file exist
  command: touch /etc/pve/storage.cfg

- name: add space glusterfs storage
  lineinfile:
    path: /etc/pve/storage.cfg
    line: "\n"
    state: present
  when: "inventory_hostname == master_machine"

- name: set glusterfs storage
  lineinfile:
    path: /etc/pve/storage.cfg
    regex: "^.*{{item}}"
    line: "{{item}}"
    state: present
  with_items:
    - "glusterfs: {{gluster_storage_name}}"
    - "  path /mnt/pve/{{gluster_storage_name}}"
    - "  volume {{gluster_brick_name}}"
    - "  content vztmpl,iso,images"
    - "  server {{master_machine}}"
    - "  server2 {{groups.all[1]}}"
  when: "inventory_hostname == master_machine"

## Mount configuration.
#- name: Ensure the Gluster volume is mounted.
#  mount:
#    name: "{{ gluster_mount_dir }}"
#    src: "{{ ansible_host }}:{{ gluster_brick_name }}"
#    fstype: glusterfs
#    opts: "defaults,_netdev"
#    state: mounted
