---
- name: Check if cluster exist
  shell: pvecm status | grep {{pve_cluster_name}} | wc -l
  register: _is_pve_cluster
  changed_when: "_is_pve_cluster.stdout != '1'"
  when: "inventory_hostname == master_machine"

- name: Create cluster
  shell: pvecm create {{pve_cluster_name}}
  when: "inventory_hostname == master_machine and _is_pve_cluster.stdout == '0'"

- name: Reboot host and wait for it to restart
  reboot:
    msg: "Reboot initiated by Ansible"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami
  when: "inventory_hostname == master_machine and _is_pve_cluster.stdout == '0'"

- name: Install expect
  apt:
    name: expect
    state: present
  when: "inventory_hostname != master_machine"

- name: Check if already in cluster
  shell: pvecm status | grep {{inventory_hostname}} | wc -l
  register: _is_pve_added_to_cluster
  changed_when: "_is_pve_added_to_cluster.stdout != '1'"

- name: Reboot host and wait for it to restart
  reboot:
    msg: "Reboot initiated by Ansible"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami
  when: "inventory_hostname != master_machine and _is_pve_added_to_cluster.stdout == '0'"

- name: add to cluster
  shell: expect -c 'spawn pvecm add {{master_machine}};
                    expect ".*password.*"; send "MotDePasse\r";
                    expect ".*(yes/no).*"; send "yes\n";
                    interact'
  throttle: 1
  when: "inventory_hostname != master_machine and _is_pve_added_to_cluster.stdout == '0'"
